name: Java CI with Maven & Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven (master.xml only)
        run: mvn clean test -Dsurefire.suiteXmlFiles=master.xml
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
      - name: Build Docker image
        run: docker build -t opencart-app .
      - name: Run Docker container
        run: |
          docker run --name opencart-test-container -d -p 8080:8080 opencart-app
          sleep 30
          docker logs opencart-test-container
          docker stop opencart-test-container
          docker rm opencart-test-container
      - name: Archive Extent HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-html-report
          path: reports/Test-Report-*.html

